version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fpl_ai_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: fpl_ai_frontend
   # volumes:
   #   - ./frontend:/app
   #   - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: fpl_ai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: